package com.rayllanderson.raybank.statement.models;

public enum BankStatementType {
    TRANSFER, DEPOSIT, BRAZILIAN_BOLETO, CREDIT_CARD_PAYMENT, INVOICE_PAYMENT, INVOICE_PAYMENT_RECEIPT, DEBIT_CARD_PAYMENT, CARD_RECEIVE_PAYMENT
}
