server:
  port: '8080'

spring:

  datasource:
    driverClassName: org.h2.Driver
    password: ''
    username: sa
    url: jdbc:h2:mem:testdb

  jpa:
    generate-ddl: 'true'
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: 'true'
    show-sql: 'true'
    properties:
      hibernate_format_sql: 'true'
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
      hibernate_show_sql: 'true'

  h2:
    console:
      enabled: 'true'

keycloak:
  realm: raybank
  server-url: http://localhost:8443
  credentials:
    client-secret: FNWh2lMeyqJgzDmpqnIvkIcReFepEiMP
    client-id: raybank-backend-generate-user