spring:
  jpa:
    properties:
      hibernate_format_sql: 'true'
      hibernate_show_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'false'

postgres:
  username: ${POSTGRES_USERNAME}
  password: ${POSTGRES_PASSWORD}
  host: ${POSTGRES_HOST}
  port: ${POSTGRES_PORT}
  schema: ${POSTGRES_SCHEMA}

keycloak:
  realm: ${KEYCLOAK_REALM}
  server-url: ${KEYCLOAK_SERVER-URL}
  credentials:
    client-secret: ${KEYCLOAK_CLIENT-ID}
    client-id: ${KEYCLOAK_CLIENT-SECRET}

boleto:
  lock:
    atLeastFor: ${BOLETO_LOCK_ATLEASTFOR:17990S}
    atMostFor: ${BOLETO_LOCK_ATMOSTFOR:17990S}
  scheduler:
    expirate: ${CONFIG_BOLETO_SCHEDULER_EXPIRATE:18000}
    process: ${CONFIG_BOLETO_SCHEDULER_PROCESS:1800}
    refund: ${CONFIG_BOLETO_SCHEDULER_REFUND:18000}
