spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.server-url}/realms/${keycloak.realm}
          jwk-set-uri: ${keycloak.server-url}/realms/${keycloak.realm}/protocol/openid-connect/certs
  profiles:
    active: local
  jpa:
    open-in-view: 'false'
raybank:
  boleto:
    postBackUrl: ${RAYBANK_BOLETO_POSTBACK_URL:http://localhost:8080/api/}