spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.server-url}/realms/${keycloak.realm}
          jwk-set-uri: ${keycloak.server-url}/realms/${keycloak.realm}/protocol/openid-connect/certs
  datasource:
    url: jdbc:postgresql://${postgres.host}:${postgres.port}/${postgres.schema}?serverTimezone=UTC
    driver-class-name: org.postgresql.Driver
    username: ${postgres.username}
    password: ${postgres.password}
  jpa:
    open-in-view: 'false'
    hibernate:
      ddl-auto: none
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      generate.statistics: false

retry:
  statement:
    create:
      maxAttempts: 5
      maxDelay: 5000
  card:
    payment:
      maxAttempts: 3
      maxDelay: 500
  maxAttempts: 3
  maxDelay: 1000

boleto:
  lock:
    atLeastFor: ${boleto.lock.atLeastFor}
    atMostFor: ${boleto.lock.atMostFor}
  scheduler:
    expirate: ${boleto.scheduler.expirate}
    process: ${boleto.scheduler.process}
    refund: ${boleto.scheduler.refund}