server:
  port: '8080'

spring:
  cloud:
    aws:
      region:
        static: ${AWS_REGION:us-east-1}
      credentials:
        access-key: ${AWS_ACCESS_KEY:kaguya}
        secret-key: ${AWS_SECRET_KEY:sama}
      sqs:
        enabled: true
        endpoint: ${SQS_ENDPOINT:http://localhost:4566}
      stack:
        auto: false
  datasource:
    driverClassName: org.h2.Driver
    password: ''
    username: sa
    url: jdbc:h2:mem:testdb

  jpa:
    generate-ddl: 'true'
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: 'true'
    show-sql: 'true'
    properties:
      hibernate_format_sql: 'true'
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
      hibernate_show_sql: 'true'

  h2:
    console:
      enabled: 'true'

keycloak:
  realm: raybank
  server-url: http://localhost:8443
  credentials:
    client-secret: FNWh2lMeyqJgzDmpqnIvkIcReFepEiMP
    client-id: raybank-backend-create-user

#every 30s
boleto:
  lock:
    atLeastFor: 29S
    atMostFor: 29S
  scheduler:
    expirate: 30
    process: 30
    refund: 30