spring:
  jpa:
    properties:
      hibernate_format_sql: 'true'
      hibernate_show_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
  cloud:
    aws:
      region:
        static: us-east-1
      credentials:
        access-key: kaguya
        secret-key: sama
      sqs:
        enabled: true
        endpoint: http://localhost:4566
      s3:
        enabled: true
        endpoint: http://s3.localhost.localstack.cloud:4566/
      stack:
        auto: false

postgres:
  username: postgres
  password: 12345
  host: localhost
  port: 5432
  schema: raybank

keycloak:
  realm: raybank
  server-url: http://localhost:8443
  servers-url-issuer-uri: https://localhost:8443/auth/realms/{realm},${keycloak.server-url}/realms/${keycloak.realm}
  credentials:
    client-secret: 8KoaQh9EpjXBN5engNI1licBfLjWdefT
    client-id: raybank-backend-create-user

invoice:
  scheduler:
    close: 30
    overdue: 30

#every 30s
boleto:
  lock:
    atLeastFor: 29S
    atMostFor: 29S
  scheduler:
    expirate: 30
    process: 30
    refund: 30