spring:
  jpa:
    properties:
      hibernate_format_sql: 'true'
      hibernate_show_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'

postgres:
  username: postgres
  password: 12345
  host: localhost
  port: 5432
  schema: raybank

keycloak:
  realm: raybank
  server-url: http://localhost:8443
  credentials:
    client-secret: 702PlTfBk922cjPGUmwkZpSAuyP6Hx1v
    client-id: raybank-backend-create-user

invoice:
  scheduler:
    close: 30
    overdue: 30

#every 30s
boleto:
  lock:
    atLeastFor: 29S
    atMostFor: 29S
  scheduler:
    expirate: 30
    process: 30
    refund: 30

kafka:
  bootstrap-server: localhost:29092