spring:
  jpa:
    hibernate:
      ddl-auto: update

postgres:
  username: ${POSTGRES_USERNAME}
  password: ${POSTGRES_PASSWORD}
  host: ${POSTGRES_HOST}
  port: ${POSTGRES_PORT}
  schema: ${POSTGRES_SCHEMA}

RESOURCE_SERVER_ISSUER: ${KEYCLOAK_SERVER-URL}/realms/${KEYCLOAK_REALM}
RESOURCE_SERVER_JWK_SET_URI: ${KEYCLOAK_SERVER-URL}/realms/${KEYCLOAK_REALM}/protocol/openid-connect/certs

keycloak:
  realm: ${KEYCLOAK_REALM}
  server-url: ${KEYCLOAK_SERVER-URL}
  credentials:
    client-id: ${KEYCLOAK_CLIENT-ID}
    client-secret: ${KEYCLOAK_CLIENT-SECRET}

boleto:
  lock:
    atLeastFor: ${BOLETO_LOCK_ATLEASTFOR:720S}
    atMostFor: ${BOLETO_LOCK_ATMOSTFOR:720S}
  scheduler:
    expirate: ${BOLETO_SCHEDULER_EXPIRATE:720}
    process: ${BOLETO_SCHEDULER_PROCESS:720}
    refund: ${BOLETO_SCHEDULER_REFUND:720}

invoice:
  lock:
    atLeastFor: ${INVOICE_LOCK_ATLEASTFOR:720}
    atMostFor: ${INVOICE_LOCK_ATMOSTFOR:720}
  scheduler:
    close: ${INVOICE_SCHEDULER_CLOSE:720}
    overdue: ${INVOICE_SCHEDULER_OVERDUE:720}