spring:
  cloud:
    aws:
      sqs:
        endpoint: ${SQS_ENDPOINT:https://sqs.us-east-1.amazonaws.com}
        region: ${SQS_REGION:us-east-1}
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE:5MB}
      max-request-size: ${MAX_FILE_SIZE:5MB}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${RESOURCE_SERVER_ISSUER}
          jwk-set-uri: ${RESOURCE_SERVER_JWK_SET_URI}
        provider:
          cognito:
            issuerUri: ${COGNITO_ISSUER_URI:}
            clientId: ${COGNITO_CLIENT_ID:}
            client-secret: ${COGNITO_CLIENT_SECRET:}
            user-name-attribute: username
  datasource:
    url: jdbc:postgresql://${postgres.host}:${postgres.port}/${postgres.schema}?serverTimezone=UTC
    driver-class-name: org.postgresql.Driver
    username: ${postgres.username}
    password: ${postgres.password}
    hikari:
      auto-commit: false
      maximum-pool-size: 10
  jpa:
    open-in-view: 'false'
    hibernate:
      ddl-auto: none
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      generate.statistics: false

retry:
  register:
    maxAttempts: 10
    maxDelay: 30000
  statement:
    create:
      maxAttempts: 5
      maxDelay: 5000
  card:
    payment:
      maxAttempts: 3
      maxDelay: 500
  maxAttempts: 3
  maxDelay: 1000

invoice:
  lock:
    atLeastFor: 1790S
    atMostFor: 1790S
  scheduler:
    close: 3600
    overdue: 3600

server:
  port: ${SERVER_PORT:8080}

sqs:
  queue-name: ${SQS_QUEUE_NAME:keycloak-event-listener-queue}
  thumbnail-queue-name: ${SQS_THUMB_QUEUE_NAME:thumbnail-event-listener-queue}
  cognito-register-queue-name: ${SQS_COGNITO_QUEUE_NAME:cognito-event-listener-queue}
s3:
  bucketName: ${AWS_S3_BUCKET_NAME:rayllanderson-raybank-bucket}

logging:
  level:
    com.rayllanderson.raybank: ${LOGGING_LEVEL:INFO}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never

oauth:
  provider-name: ${OAUTH_PROVIDER_NAME:keycloak}