spring:
  jpa:
    hibernate:
      ddl-auto: update

postgres:
  username: ${POSTGRES_USERNAME}
  password: ${POSTGRES_PASSWORD}
  host: ${POSTGRES_HOST}
  port: ${POSTGRES_PORT}
  schema: ${POSTGRES_SCHEMA}

keycloak:
  realm: ${KEYCLOAK_REALM}
  server-url: ${KEYCLOAK_SERVER-URL}
  credentials:
    client-id: ${KEYCLOAK_CLIENT-ID}
    client-secret: ${KEYCLOAK_CLIENT-SECRET}

boleto:
  lock:
    atLeastFor: ${BOLETO_LOCK_ATLEASTFOR:7200S}
    atMostFor: ${BOLETO_LOCK_ATMOSTFOR:7200S}
  scheduler:
    expirate: ${CONFIG_BOLETO_SCHEDULER_EXPIRATE:7200 }
    process: ${CONFIG_BOLETO_SCHEDULER_PROCESS:7200 }
    refund: ${CONFIG_BOLETO_SCHEDULER_REFUND:7200 }

invoice:
  scheduler:
    close: ${CONFIG_INVOICE_SCHEDULER_CLOSE:7200 }
    overdue: ${CONFIG_INVOICE_SCHEDULER_OVERDUE:7200 }