version: '3.7'

services:
  raybank:
    container_name: raybank
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - SPRING_PROFILES_ACTIVE=hom
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_SCHEMA=raybank
      - KEYCLOAK_REALM=raybank
      - KEYCLOAK_SERVER-URL=http://keycloak:8080
      - KEYCLOAK_CLIENT-ID=raybank-backend-create-user
      - KEYCLOAK_CLIENT-SECRET=2sSe4b3gdsi8QjQeAAsyIEaIK99E0YCq
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - keycloak
    networks:
      - raybank-network

  postgres:
    image: 'postgres:alpine'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 12345
    volumes:
      - C:/docker/volumes/raybank/postgres:/var/lib/postgresql/data
    networks:
      - raybank-network

  teste-pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "root@root.com"
      PGADMIN_DEFAULT_PASSWORD: "12345"
    ports:
      - "16543:80"
    depends_on:
      - postgres
    networks:
      - raybank-network

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:20.0.3
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_IMPORT=/opt/jboss/keycloak/imports/realm-export.json
      - -Dkeycloak.profile.feature.upload_scripts=enabled
      - DB_VENDOR=POSTGRES
      - DB_ADDR=keycloak-postgres
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=keycloak
    ports:
      - "8443:8080"
    command:
      - start-dev # uma versão mais leve customizada para ambiente de desenvolvimento e testes pensada para rodar na máquina do desenvolvedor
      - -Dkeycloak.import=/opt/jboss/keycloak/imports/realm-export.json
      - --import-realm
    volumes:
      - C:/docker/volumes/raybank/keycloak/imports:/opt/jboss/keycloak/imports
      - C:/docker/volumes/raybank/keycloak/provider/custom-event-listener.jar:/opt/keycloak/providers/custom-event-listener.jar
    depends_on:
      - keycloak-postgres
    networks:
      - raybank-network

  keycloak-postgres:
    image: 'postgres:alpine'
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - C:/docker/volumes/raybank/keycloak-postgres:/var/lib/postgresql/data
    networks:
      - raybank-network

networks:
  raybank-network:
    driver: bridge