version: '3.7'

services:
  raybank:
    image: rayllanderson/raybank:latest
    container_name: raybank
    environment:
      - SPRING_PROFILES_ACTIVE=hom
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_SCHEMA=raybank
      - KAFKA_BOOTSTRAP-SERVER=kafka:9092
      - KEYCLOAK_REALM=raybank
      - KEYCLOAK_SERVER-URL=http://keycloak:8080
      - KEYCLOAK_CLIENT-ID=raybank-backend-create-user
      - KEYCLOAK_CLIENT-SECRET=8KoaQh9EpjXBN5engNI1licBfLjWdefT
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - keycloak
    networks:
      - raybank-network

  postgres:
    image: 'postgres:alpine'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: raybank
      POSTGRES_PASSWORD: 12345
    volumes:
      - ./docker-volumes/postgres:/var/lib/postgresql/data
    networks:
      - raybank-network

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:20.0.3
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_IMPORT=/opt/jboss/keycloak/imports/realm-export.json
      - KC_SQS_QUEUE=keycloak-event-listener-queue
      - -Dkeycloak.profile.feature.upload_scripts=enabled
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=kaguya
      - AWS_SECRET_ACCESS_KEY=shinomiya
      - SQS_LOCAL=true
      - SQS_LOCAL_URL=http://localstack:4566
    ports:
      - "8443:8080"
    command:
      - start-dev # uma versão mais leve customizada para ambiente de desenvolvimento e testes pensada para rodar na máquina do desenvolvedor
      - -Dkeycloak.import=/opt/jboss/keycloak/imports/realm-export.json
      - --import-realm
    volumes:
      - ./docker-volumes/keycloak/imports:/opt/jboss/keycloak/imports
      - ./docker-volumes/keycloak/provider/custom-event-listener-jar-with-dependencies.jar:/opt/keycloak/providers/custom-event-listener-jar-with-dependencies.jar
    networks:
      - raybank-network

  localstack:
    container_name: localstack
    image: localstack/localstack:3.0.2
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs
      - AWS_DEFAULT_REGION=us-east-1
      - DEBUG=1
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./script/init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh"
      - "./script/init-aws.sh:/docker-entrypoint-initaws.d/init-aws.sh"
    networks:
      - raybank-network

# enable if you want to keycloak spi with kafka
  # zookeeper:
  #   image: confluentinc/cp-zookeeper:6.0.0
  #   environment:
  #     ZOOKEEPER_CLIENT_PORT: 2181
  #   networks:
  #     - raybank-network

  # kafka:
  #   image: confluentinc/cp-kafka:6.0.0
  #   depends_on:
  #     - zookeeper
  #   ports:
  #     - "29092:9092"
  #   environment:
  #     KAFKA_BROKER_ID: 1
  #     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  #     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
  #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
  #     KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
  #     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  #   networks:
  #     - raybank-network

  # # This "container" is a workaround to pre-create topics
  # kafka-setup:
  #   image: confluentinc/cp-kafka:6.0.0
  #   hostname: kafka-setup
  #   depends_on:
  #     - kafka
  #   command: "bash -c 'echo Waiting for Kafka to be ready... && \
  #                              cub kafka-ready -b kafka:9092 1 20 && \
  #                              kafka-topics --create --if-not-exists --zookeeper zookeeper:2181 --partitions 3 --replication-factor 1 --config retention.ms=10000 --topic keycloak-event-listener-topic'"
  #   environment:
  #     # The following settings are listed here only to satisfy the image's requirements.
  #     # We override the image's `command` anyways, hence this container will not start a broker.
  #     KAFKA_BROKER_ID: ignored
  #     KAFKA_ZOOKEEPER_CONNECT: ignored
  #   networks:
  #     - raybank-network

networks:
  raybank-network:
    driver: bridge