services:
  raybank:
    image: rayllanderson/raybank:latest
    container_name: raybank
    restart: on-failure
    environment:
      - SPRING_PROFILES_ACTIVE=hom
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
      - POSTGRES_SCHEMA=raybank
      - KEYCLOAK_REALM=raybank
      - KEYCLOAK_SERVER-URL=http://localhost:8443
      - KEYCLOAK_CLIENT-ID=raybank-backend-create-user
      - KEYCLOAK_CLIENT-SECRET=8KoaQh9EpjXBN5engNI1licBfLjWdefT
      - S3_ENDPOINT=http://s3.localhost.localstack.cloud:4566/
      - SQS_ENDPOINT=http://localhost:4566
    depends_on:
      - postgres
      - keycloak
    network_mode: "service:localhost"
    
  raybank-frontend:
    image: rayllanderson/raybank-nextjs-app:latest
    environment:
      - NODE_ENV=development
    env_file:
      - ../frontend/.env.local
    network_mode: "service:localhost"

  postgres:
    image: 'rayllanderson/raybank-custom-postgress:latest'
    network_mode: "service:localhost"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    container_name: keycloak
    image: rayllanderson/raybank-keycloak:v0
    environment:
      - SQS_LOCAL_URL=http://localhost:4566
    command:
      - start-dev # uma versão mais leve customizada para ambiente de desenvolvimento e testes pensada para rodar na máquina do desenvolvedor
      - --import-realm
      - -Dkeycloak.import=/opt/jboss/keycloak/imports/realm-export.json
      - --http-port=8443
    volumes:
      - "./docker-volumes/keycloak/imports/realm-export.json:/opt/jboss/keycloak/imports/realm-export.json"
    network_mode: "service:localhost"

  localstack:
    container_name: localstack
    # image: localstack/localstack:3.0.2
    build:
      context: localstack/.
      dockerfile: Dockerfile
    environment:
      - SERVICES=sqs,s3,lambda
      - AWS_DEFAULT_REGION=us-east-1
      - DEBUG=1
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./lambda/:/opt/code/lambda"
      - "./localstack/terraform:/opt/code/localstack/terraform"
      - "./localstack/script/init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh"
      - "./localstack/script/init-aws.sh:/docker-entrypoint-initaws.d/init-aws.sh"
    network_mode: "service:localhost"

  localhost:
    image: alpine:latest
    command: sleep infinity
    ports:
    - "8443:8443" # Keycloak
    - "8080:8080" # raybank backend port
    - "5432:5432" # postgres
    - "4566:4566" # SQS
    - "4572:4572" # S3
    - "3000:3000" # raybank frontend