package com.rayllanderson.raybank.transaction.models;

public enum TransactionType {
    TRANSFER, DEPOSIT, BRAZILIAN_BOLETO,
    CREDIT_CARD_PAYMENT, DEBIT_CARD_PAYMENT, CARD_RECEIVE_PAYMENT, CREDITING_CARD, CREDIT_CARD_REFUND,
    INVOICE_PAYMENT, INVOICE_PAYMENT_RECEIPT
}
