# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package & Publish to Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn clean install -Dmaven.test.skip=true
      working-directory: ./v2/backend

    - name: Set env
      run: echo "DATE=$(date +%s)" >> $GITHUB_ENV

    - name: Build the Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./v2/backend
        dockerfile: Dockerfile
        push: false
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/raybank:${{ env.DATE }}

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Push the Docker image to Docker Hub
      uses: docker/build-push-action@v4
      with:
        context: ./v2/backend
        dockerfile: Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/raybank:${{ env.DATE }}
